### ISSUE TITLE
Create and deploy a timelock program

### ISSUE THREAD

**Issue by metaproph3t** [metaDAOproject/solana-timelock#4]
We should create and deploy a program that allows for delayed execution of SVM instructions. This would bolster the *security* and *manipulation-resistance* of MetaDAO and allow us to shorten proposal times.

Imagine that proposal times are 1 day and the timelock delay is 3 days. Then, even if a malicious proposal goes through, someone can raise a follow-up proposal to cancel the malicious instruction.

This would also raise the cost to manipulate. Today, someone who wants a proposal to pass can place high bids in the pass market. Those bids are only filled if the proposal goes through, so the manipulator isn't taking much risk. But with a timelock, you could have a manipulator's high bids get filled and then the proposal get cancelled.

**Comment by Henry-E** [comment]
Done in #5 . The last piece is to mark the program as no longer upgradeable.
